### ISSUE TITLE
Support logging of arbitrary data

### ISSUE THREAD

**Issue by berkowitzi** [lightstep/ls-trace-py#15]
Looking at the implementation of `log_kv` from this datadog-originated library, it looks like DataDog has removed/not implemented functionality to allow arbitrary key/value pairs to be logged. It would be great if the LightStep-forked version of the ddtrace library could permit this.

See implementation here: https://github.com/DataDog/dd-trace-py/blob/564ac41a4ff07595266c6ccd7d4503da114f1464/ddtrace/opentracer/span.py#L80

**Comment by kavehhh** [comment]
@berkowitzi and I chatted about this irl. We'll be closing this for now, but the work in OpenTelemetry will allow for adding logs to spans.
